name: Build and Push Docker Image

on:
  push:
    # Run on pushes to the 'main' branch
    branches: [ "main" ]
    # ALSO run on pushes of tags that start with 'v' (e.g., v1, v2.0, v1.2.3)
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # This step is smart!
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-hello-world
          tags: |
            # This creates the ':main' tag on a push to main
            type=ref,event=branch
            
            # This creates the ':v2' tag on a push of a tag 'v2'
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # This 'meta' step will output the correct tag automatically
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}